# Generated by Django 2.1.5 on 2019-02-03 04:38

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_url', models.CharField(max_length=255)),
                ('internal_url', models.CharField(max_length=255)),
                ('m_format', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.Candidate')),
            ],
            options={
                'verbose_name': 'AnswerMedia',
                'verbose_name_plural': 'AnswerMedia',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('reference_answer', models.TextField(blank=True, default=None, null=True)),
                ('keywords_csv', django_mysql.models.SetTextField(models.CharField(blank=True, max_length=70), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.Candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.Candidate')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.Media')),
            ],
            options={
                'verbose_name': 'AnswerText',
                'verbose_name_plural': 'AnswerText',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.Question'),
        ),
    ]
