# Generated by Django 2.1.2 on 2019-02-02 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_url', models.CharField(max_length=255)),
                ('internal_url', models.CharField(max_length=255)),
                ('m_format', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.Media')),
            ],
        ),
    ]
