# Generated by Django 2.1.5 on 2019-02-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0002_text_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Text', to='media_manager.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='similarity_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
