# Generated by Django 2.1.5 on 2019-02-11 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_score_entities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='internal_url',
        ),
        migrations.AlterField(
            model_name='text',
            name='media',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_manager.Media'),
        ),
        migrations.AlterField(
            model_name='text',
            name='score',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_manager.Score'),
        ),
    ]
